server:
  port: 10009

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/nasadb
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: NASA-SERVICE

# Logging configuration
logging:
  level:
    root: INFO
    com.nasa.prueba.aspirante: DEBUG