version: '3.8'
services:
  postgres:
    container_name: nasadb
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql    
      - nasa_data:/var/lib/postgresql/data

volumes:
  nasa_data:      
